### ISSUE TITLE
Column layout breaks in Chrome

### ISSUE THREAD

**Issue by johnmeredith** [codebushi/gatsby-starter-forty#7] opened 2019-01-04 13:38 UTC
Hi there,
I noticed that the way columns and images are resolved in Chrome differs. Opening up the [https://gatsby-forty.surge.sh/elements](https://gatsby-forty.surge.sh/elements) page in chrome seems to be forcing a mobile view? In Firefox it looks great. For comparison, my cloned page [here](https://www.interop.live/speakers/) displays the same behaviour in different browsers. Can a maximum image size be enforced?

**Comment by ChangoMan** [comment] 2019-01-12 18:16
Hi John,
I'm not able to reproduce your issue on my Chrome. Everything looks fine on my end, it's not being forced to a mobile view. I'm wondering if you have some sort of chrome extension or mobile emulation turned on?

**Comment by ChangoMan** [comment] 2019-02-02 17:36
Closing this issue due to inability to reproduce.

**Closed as completed** 2019-02-02 17:36 UTC
